#FROM python:3.8-slim-buster
RUN pip install --upgrade pip
# RUN apk update
# RUN apk add make automake gcc g++ subversion python3-dev
# EXPOSE 5001
WORKDIR /mainapi
ADD . /mainapi
RUN pip install --ignore-installed pip && pip install pip==8.0.2
RUN pip install -r requirements.txt

ENTRYPOINT [ "python" ]

CMD [ "api.py" ]
